import type { Metadata } from "next";
import "./globals.css";
import { Footer } from "@/components/Footer";
import { Navigation } from "@/components/Navigation";
import { BackToTop } from "@/components/BackToTop";
import { ParticlesBackground } from "@/components/ParticlesBackground";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="antialiased bg-background text-foreground font-poppins-cdn">
        <div className="fixed inset-0 z-[-1]">
          <ParticlesBackground />
        </div>
        <Navigation />
        {children}
        <BackToTop />
        <Footer />
      </body>
    </html>
  );
}
